version: "3.8"

services:
  collabform-app:
    build: .
    container_name: collabform-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
